### PR TITLE
Add initial helm chart implementation

### PR DESCRIPTION
**Pull request by sedadas**
The aim of this PR is to add an initial implementation of helm charts for wger.
The PR will be updated periodically until the charts are usable and it will be unmarked as a draft

### CODE REVIEW

**Comment by rolandgeider** [comment]
Great, thank you!

**Comment by sedadas** [comment]
@rolandgeider I managed to bring the helm charts to a functioning state:
* running ephemeral deployments without any persistence works
* running deployments with persistence works
* the ingress works (thanks to the annotations, cert-manager integration works as well)

You can test an ephemeral deployment using minikube the instructions in the README.

Please tell me if you've run into something that I may need to fix.

Also, when we get the PR merged, it would be a good idea to improve the CI/CD pipeline so that the chart gets packaged and uploaded to Github pages.

**Comment by rolandgeider** [comment]
Just only glanced over this but wow! Such a great PR, README, ci, it has everything. Thanks so much

**Comment by rolandgeider** [comment]
Sorry, haven't found the time to test this. Can it be that there might be some problems with the redis connection? Somebody encountered a problem during startup: #2

**Comment by rolandgeider** [comment]
This took a bit longer than I had thought. In any case, many many thanks for the PR

**Pull request merged**
