### PR TITLE
Added github chart-release and converted statefulset to deployment

### PR DESCRIPTION
**Pull request by InputObject2**
Sorry for the wall of text, there were a lot of modifications done. Mostly I updated the chart, added a workflow and fixed minor bugs.

Also, if you approve this, you'll need to create a branch called `gh-pages` so that the chart-release can put the new releases there.

- Created a chart-release.yml github action to create new releases and publish a chart whenever this repo is updated.
- Moved chart to subfolder `charts/wger` to match what is done in other repos.
- Updated postgres and redis to the latest bitnami charts.
- Fixed the values no longer matching with the latest bitnami charts
- Set the ingress as it's own block for the variables.
- Set the http service as it's own block for the variables.
- Converted statefulset to deployment as a stateless webserver should not be a statefulset.
- Added default values to log email to console since I couldn't get this to work without it being present.
- Fixed disabling ingress not working
- Added pvc for media and static so they can be shared by all the webserver instances.
- Updated readme to match all the changes
- New release v0.1.2 (lots of smaller in-between fixes are squashed in this PR)

Chart will now be installable with 

```bash
helm repo add github-wger https://wger-project.github.io/helm-charts

helm upgrade \
  --install wger github-wger/wger \
  --version 0.1.2 \
  --namespace wger \
  --create-namespace
```

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks!!

@sedadas thoughts?

**Comment by InputObject2** [comment]
I'll try to get linting working, helm lint is not giving me anything and I fixed all the yamllint errors. 

For the packaging errors, the integration needs a branch called "gh-pages" to exist.

**Comment by rolandgeider** [comment]
Something did get published (https://wger-project.github.io/helm-charts/), but it seems the release didn't work, is there any other setting I need to change?

**Comment by rolandgeider** [comment]
it seems the packaging errors are because your user is not allowed to create releases, should be work once this is merged to master. Don't know what to do about the name lint, everything seems to have a name in persistent-volume-claim.yml

**Pull request merged**
