### PR TITLE
update dependancies & Fix moutn perms

### PR DESCRIPTION
**Pull request by MarcCoxall-SMARSH**

### CODE REVIEW

**Comment by bbkz** [comment]
I don't think the *.tgz archives are ment to be committed into the repository, shouldn't they be fetched with:

```bash
helm dependency update
```

I suggest adding `charts/wger/charts/*.tgz` to the `.gitignore`.

Yours,
bbk

**Comment by rolandgeider** [comment]
(derailing thread a bit) @bbkz thanks for answering here. I also just saw that nothing had happened with your other PRs. Since I know basically nothing about helm charts, would you like to maintain this repo?

**Comment by ninjatec** [comment]
@rolandgeider @bbkz I am happy to help with helm, but I am quite new to the project and it looks like helm needs some work to fully use the functionality of the latest docker. 

I need to do quite a bit more research before I can make a meaningful contribution.

**Comment by bbkz** [comment]
@rolandgeider Sure i'd like to maintain the repo. As this would be my first steps maintaining a open source repo, please be gentle ;-)

@ninjatec I use k3s for my kubernetes cluster but as far is i know even vanilla kubernetes doesn't need docker to run, they use containerd. So i am not sure what you are thinking about. If you like you can try out my `final` branch in my fork.

* https://github.com/bbkz/wger-helm-charts/tree/final

If i will maintain this repo, this will get merged here.

**Comment by ninjatec** [comment]
My note was referencing the newer dockerfile image containing several components, wger celery ngix etc.
My thinking was to run more containers in the pod with each one performing a distinct job. 

But like I say I am pretty new to the project so I was not planning to re-architect the helm chart without first understanding the system much better. Hence why i deleted my fork until I can learn more. But I am happy to contribute to the project and pick up any issues that get raised as part of moving the helm forward.

**Comment by ninjatec** [comment]
I will add issues for the things I was working on so they can be managed properly

**Pull request closed without merging**
